// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"gopkg.in/mgo.v2/bson"
)

type status int
const (
    INPROGRESS status = iota
    WON
    LOST
)

type Game struct {
	ID          bson.ObjectId `bson:"_id" json:"id"`
	PlayerName string `bson:"playername" json:"playername"`
	Word string `bson:"word" json:"word"`
	Answers []int `bson:"answers" json:"answers"`
}
